### ISSUE TITLE
[기능] 회원 - 특정 회원 정보 조회

### ISSUE THREAD

**Issue by yeonssu** [codestates-seb/seb43_pre_035#32]
### Tasks
- [x] 관련된 Controller, Service, Repository 구현
- [x] 관련된 DTO, Entity 구현
- [x] 관련된 Method 구현

### Estimated task time
3hr
